package com.sloydev.dependencyinjectionperformance.winter

import com.sloydev.dependencyinjectionperformance.*
import io.jentz.winter.component

val winterKotlinComponent = component {
    prototype { Fib1() }
    prototype { Fib2() }
    prototype { Fib3(instance(), instance()) }
    prototype { Fib4(instance(), instance()) }
    prototype { Fib5(instance(), instance()) }
    prototype { Fib6(instance(), instance()) }
    prototype { Fib7(instance(), instance()) }
    prototype { Fib8(instance(), instance()) }
    prototype { Fib9(instance(), instance()) }
    prototype { Fib10(instance(), instance()) }
    prototype { Fib11(instance(), instance()) }
    prototype { Fib12(instance(), instance()) }
    prototype { Fib13(instance(), instance()) }
    prototype { Fib14(instance(), instance()) }
    prototype { Fib15(instance(), instance()) }
    prototype { Fib16(instance(), instance()) }
    prototype { Fib17(instance(), instance()) }
    prototype { Fib18(instance(), instance()) }
    prototype { Fib19(instance(), instance()) }
    prototype { Fib20(instance(), instance()) }
    prototype { Fib21(instance(), instance()) }
    prototype { Fib22(instance(), instance()) }
    prototype { Fib23(instance(), instance()) }
    prototype { Fib24(instance(), instance()) }
    prototype { Fib25(instance(), instance()) }
    prototype { Fib26(instance(), instance()) }
    prototype { Fib27(instance(), instance()) }
    prototype { Fib28(instance(), instance()) }
    prototype { Fib29(instance(), instance()) }
    prototype { Fib30(instance(), instance()) }
    prototype { Fib31(instance(), instance()) }
    prototype { Fib32(instance(), instance()) }
    prototype { Fib33(instance(), instance()) }
    prototype { Fib34(instance(), instance()) }
    prototype { Fib35(instance(), instance()) }
    prototype { Fib36(instance(), instance()) }
    prototype { Fib37(instance(), instance()) }
    prototype { Fib38(instance(), instance()) }
    prototype { Fib39(instance(), instance()) }
    prototype { Fib40(instance(), instance()) }
    prototype { Fib41(instance(), instance()) }
    prototype { Fib42(instance(), instance()) }
    prototype { Fib43(instance(), instance()) }
    prototype { Fib44(instance(), instance()) }
    prototype { Fib45(instance(), instance()) }
    prototype { Fib46(instance(), instance()) }
    prototype { Fib47(instance(), instance()) }
    prototype { Fib48(instance(), instance()) }
    prototype { Fib49(instance(), instance()) }
    prototype { Fib50(instance(), instance()) }
    prototype { Fib51(instance(), instance()) }
    prototype { Fib52(instance(), instance()) }
    prototype { Fib53(instance(), instance()) }
    prototype { Fib54(instance(), instance()) }
    prototype { Fib55(instance(), instance()) }
    prototype { Fib56(instance(), instance()) }
    prototype { Fib57(instance(), instance()) }
    prototype { Fib58(instance(), instance()) }
    prototype { Fib59(instance(), instance()) }
    prototype { Fib60(instance(), instance()) }
    prototype { Fib61(instance(), instance()) }
    prototype { Fib62(instance(), instance()) }
    prototype { Fib63(instance(), instance()) }
    prototype { Fib64(instance(), instance()) }
    prototype { Fib65(instance(), instance()) }
    prototype { Fib66(instance(), instance()) }
    prototype { Fib67(instance(), instance()) }
    prototype { Fib68(instance(), instance()) }
    prototype { Fib69(instance(), instance()) }
    prototype { Fib70(instance(), instance()) }
    prototype { Fib71(instance(), instance()) }
    prototype { Fib72(instance(), instance()) }
    prototype { Fib73(instance(), instance()) }
    prototype { Fib74(instance(), instance()) }
    prototype { Fib75(instance(), instance()) }
    prototype { Fib76(instance(), instance()) }
    prototype { Fib77(instance(), instance()) }
    prototype { Fib78(instance(), instance()) }
    prototype { Fib79(instance(), instance()) }
    prototype { Fib80(instance(), instance()) }
    prototype { Fib81(instance(), instance()) }
    prototype { Fib82(instance(), instance()) }
    prototype { Fib83(instance(), instance()) }
    prototype { Fib84(instance(), instance()) }
    prototype { Fib85(instance(), instance()) }
    prototype { Fib86(instance(), instance()) }
    prototype { Fib87(instance(), instance()) }
    prototype { Fib88(instance(), instance()) }
    prototype { Fib89(instance(), instance()) }
    prototype { Fib90(instance(), instance()) }
    prototype { Fib91(instance(), instance()) }
    prototype { Fib92(instance(), instance()) }
    prototype { Fib93(instance(), instance()) }
    prototype { Fib94(instance(), instance()) }
    prototype { Fib95(instance(), instance()) }
    prototype { Fib96(instance(), instance()) }
    prototype { Fib97(instance(), instance()) }
    prototype { Fib98(instance(), instance()) }
    prototype { Fib99(instance(), instance()) }
    prototype { Fib100(instance(), instance()) }
    prototype { Fib101(instance(), instance()) }
    prototype { Fib102(instance(), instance()) }
    prototype { Fib103(instance(), instance()) }
    prototype { Fib104(instance(), instance()) }
    prototype { Fib105(instance(), instance()) }
    prototype { Fib106(instance(), instance()) }
    prototype { Fib107(instance(), instance()) }
    prototype { Fib108(instance(), instance()) }
    prototype { Fib109(instance(), instance()) }
    prototype { Fib110(instance(), instance()) }
    prototype { Fib111(instance(), instance()) }
    prototype { Fib112(instance(), instance()) }
    prototype { Fib113(instance(), instance()) }
    prototype { Fib114(instance(), instance()) }
    prototype { Fib115(instance(), instance()) }
    prototype { Fib116(instance(), instance()) }
    prototype { Fib117(instance(), instance()) }
    prototype { Fib118(instance(), instance()) }
    prototype { Fib119(instance(), instance()) }
    prototype { Fib120(instance(), instance()) }
    prototype { Fib121(instance(), instance()) }
    prototype { Fib122(instance(), instance()) }
    prototype { Fib123(instance(), instance()) }
    prototype { Fib124(instance(), instance()) }
    prototype { Fib125(instance(), instance()) }
    prototype { Fib126(instance(), instance()) }
    prototype { Fib127(instance(), instance()) }
    prototype { Fib128(instance(), instance()) }
    prototype { Fib129(instance(), instance()) }
    prototype { Fib130(instance(), instance()) }
    prototype { Fib131(instance(), instance()) }
    prototype { Fib132(instance(), instance()) }
    prototype { Fib133(instance(), instance()) }
    prototype { Fib134(instance(), instance()) }
    prototype { Fib135(instance(), instance()) }
    prototype { Fib136(instance(), instance()) }
    prototype { Fib137(instance(), instance()) }
    prototype { Fib138(instance(), instance()) }
    prototype { Fib139(instance(), instance()) }
    prototype { Fib140(instance(), instance()) }
    prototype { Fib141(instance(), instance()) }
    prototype { Fib142(instance(), instance()) }
    prototype { Fib143(instance(), instance()) }
    prototype { Fib144(instance(), instance()) }
    prototype { Fib145(instance(), instance()) }
    prototype { Fib146(instance(), instance()) }
    prototype { Fib147(instance(), instance()) }
    prototype { Fib148(instance(), instance()) }
    prototype { Fib149(instance(), instance()) }
    prototype { Fib150(instance(), instance()) }
    prototype { Fib151(instance(), instance()) }
    prototype { Fib152(instance(), instance()) }
    prototype { Fib153(instance(), instance()) }
    prototype { Fib154(instance(), instance()) }
    prototype { Fib155(instance(), instance()) }
    prototype { Fib156(instance(), instance()) }
    prototype { Fib157(instance(), instance()) }
    prototype { Fib158(instance(), instance()) }
    prototype { Fib159(instance(), instance()) }
    prototype { Fib160(instance(), instance()) }
    prototype { Fib161(instance(), instance()) }
    prototype { Fib162(instance(), instance()) }
    prototype { Fib163(instance(), instance()) }
    prototype { Fib164(instance(), instance()) }
    prototype { Fib165(instance(), instance()) }
    prototype { Fib166(instance(), instance()) }
    prototype { Fib167(instance(), instance()) }
    prototype { Fib168(instance(), instance()) }
    prototype { Fib169(instance(), instance()) }
    prototype { Fib170(instance(), instance()) }
    prototype { Fib171(instance(), instance()) }
    prototype { Fib172(instance(), instance()) }
    prototype { Fib173(instance(), instance()) }
    prototype { Fib174(instance(), instance()) }
    prototype { Fib175(instance(), instance()) }
    prototype { Fib176(instance(), instance()) }
    prototype { Fib177(instance(), instance()) }
    prototype { Fib178(instance(), instance()) }
    prototype { Fib179(instance(), instance()) }
    prototype { Fib180(instance(), instance()) }
    prototype { Fib181(instance(), instance()) }
    prototype { Fib182(instance(), instance()) }
    prototype { Fib183(instance(), instance()) }
    prototype { Fib184(instance(), instance()) }
    prototype { Fib185(instance(), instance()) }
    prototype { Fib186(instance(), instance()) }
    prototype { Fib187(instance(), instance()) }
    prototype { Fib188(instance(), instance()) }
    prototype { Fib189(instance(), instance()) }
    prototype { Fib190(instance(), instance()) }
    prototype { Fib191(instance(), instance()) }
    prototype { Fib192(instance(), instance()) }
    prototype { Fib193(instance(), instance()) }
    prototype { Fib194(instance(), instance()) }
    prototype { Fib195(instance(), instance()) }
    prototype { Fib196(instance(), instance()) }
    prototype { Fib197(instance(), instance()) }
    prototype { Fib198(instance(), instance()) }
    prototype { Fib199(instance(), instance()) }
    prototype { Fib200(instance(), instance()) }
    prototype { Fib201(instance(), instance()) }
    prototype { Fib202(instance(), instance()) }
    prototype { Fib203(instance(), instance()) }
    prototype { Fib204(instance(), instance()) }
    prototype { Fib205(instance(), instance()) }
    prototype { Fib206(instance(), instance()) }
    prototype { Fib207(instance(), instance()) }
    prototype { Fib208(instance(), instance()) }
    prototype { Fib209(instance(), instance()) }
    prototype { Fib210(instance(), instance()) }
    prototype { Fib211(instance(), instance()) }
    prototype { Fib212(instance(), instance()) }
    prototype { Fib213(instance(), instance()) }
    prototype { Fib214(instance(), instance()) }
    prototype { Fib215(instance(), instance()) }
    prototype { Fib216(instance(), instance()) }
    prototype { Fib217(instance(), instance()) }
    prototype { Fib218(instance(), instance()) }
    prototype { Fib219(instance(), instance()) }
    prototype { Fib220(instance(), instance()) }
    prototype { Fib221(instance(), instance()) }
    prototype { Fib222(instance(), instance()) }
    prototype { Fib223(instance(), instance()) }
    prototype { Fib224(instance(), instance()) }
    prototype { Fib225(instance(), instance()) }
    prototype { Fib226(instance(), instance()) }
    prototype { Fib227(instance(), instance()) }
    prototype { Fib228(instance(), instance()) }
    prototype { Fib229(instance(), instance()) }
    prototype { Fib230(instance(), instance()) }
    prototype { Fib231(instance(), instance()) }
    prototype { Fib232(instance(), instance()) }
    prototype { Fib233(instance(), instance()) }
    prototype { Fib234(instance(), instance()) }
    prototype { Fib235(instance(), instance()) }
    prototype { Fib236(instance(), instance()) }
    prototype { Fib237(instance(), instance()) }
    prototype { Fib238(instance(), instance()) }
    prototype { Fib239(instance(), instance()) }
    prototype { Fib240(instance(), instance()) }
    prototype { Fib241(instance(), instance()) }
    prototype { Fib242(instance(), instance()) }
    prototype { Fib243(instance(), instance()) }
    prototype { Fib244(instance(), instance()) }
    prototype { Fib245(instance(), instance()) }
    prototype { Fib246(instance(), instance()) }
    prototype { Fib247(instance(), instance()) }
    prototype { Fib248(instance(), instance()) }
    prototype { Fib249(instance(), instance()) }
    prototype { Fib250(instance(), instance()) }
    prototype { Fib251(instance(), instance()) }
    prototype { Fib252(instance(), instance()) }
    prototype { Fib253(instance(), instance()) }
    prototype { Fib254(instance(), instance()) }
    prototype { Fib255(instance(), instance()) }
    prototype { Fib256(instance(), instance()) }
    prototype { Fib257(instance(), instance()) }
    prototype { Fib258(instance(), instance()) }
    prototype { Fib259(instance(), instance()) }
    prototype { Fib260(instance(), instance()) }
    prototype { Fib261(instance(), instance()) }
    prototype { Fib262(instance(), instance()) }
    prototype { Fib263(instance(), instance()) }
    prototype { Fib264(instance(), instance()) }
    prototype { Fib265(instance(), instance()) }
    prototype { Fib266(instance(), instance()) }
    prototype { Fib267(instance(), instance()) }
    prototype { Fib268(instance(), instance()) }
    prototype { Fib269(instance(), instance()) }
    prototype { Fib270(instance(), instance()) }
    prototype { Fib271(instance(), instance()) }
    prototype { Fib272(instance(), instance()) }
    prototype { Fib273(instance(), instance()) }
    prototype { Fib274(instance(), instance()) }
    prototype { Fib275(instance(), instance()) }
    prototype { Fib276(instance(), instance()) }
    prototype { Fib277(instance(), instance()) }
    prototype { Fib278(instance(), instance()) }
    prototype { Fib279(instance(), instance()) }
    prototype { Fib280(instance(), instance()) }
    prototype { Fib281(instance(), instance()) }
    prototype { Fib282(instance(), instance()) }
    prototype { Fib283(instance(), instance()) }
    prototype { Fib284(instance(), instance()) }
    prototype { Fib285(instance(), instance()) }
    prototype { Fib286(instance(), instance()) }
    prototype { Fib287(instance(), instance()) }
    prototype { Fib288(instance(), instance()) }
    prototype { Fib289(instance(), instance()) }
    prototype { Fib290(instance(), instance()) }
    prototype { Fib291(instance(), instance()) }
    prototype { Fib292(instance(), instance()) }
    prototype { Fib293(instance(), instance()) }
    prototype { Fib294(instance(), instance()) }
    prototype { Fib295(instance(), instance()) }
    prototype { Fib296(instance(), instance()) }
    prototype { Fib297(instance(), instance()) }
    prototype { Fib298(instance(), instance()) }
    prototype { Fib299(instance(), instance()) }
    prototype { Fib300(instance(), instance()) }
    prototype { Fib301(instance(), instance()) }
    prototype { Fib302(instance(), instance()) }
    prototype { Fib303(instance(), instance()) }
    prototype { Fib304(instance(), instance()) }
    prototype { Fib305(instance(), instance()) }
    prototype { Fib306(instance(), instance()) }
    prototype { Fib307(instance(), instance()) }
    prototype { Fib308(instance(), instance()) }
    prototype { Fib309(instance(), instance()) }
    prototype { Fib310(instance(), instance()) }
    prototype { Fib311(instance(), instance()) }
    prototype { Fib312(instance(), instance()) }
    prototype { Fib313(instance(), instance()) }
    prototype { Fib314(instance(), instance()) }
    prototype { Fib315(instance(), instance()) }
    prototype { Fib316(instance(), instance()) }
    prototype { Fib317(instance(), instance()) }
    prototype { Fib318(instance(), instance()) }
    prototype { Fib319(instance(), instance()) }
    prototype { Fib320(instance(), instance()) }
    prototype { Fib321(instance(), instance()) }
    prototype { Fib322(instance(), instance()) }
    prototype { Fib323(instance(), instance()) }
    prototype { Fib324(instance(), instance()) }
    prototype { Fib325(instance(), instance()) }
    prototype { Fib326(instance(), instance()) }
    prototype { Fib327(instance(), instance()) }
    prototype { Fib328(instance(), instance()) }
    prototype { Fib329(instance(), instance()) }
    prototype { Fib330(instance(), instance()) }
    prototype { Fib331(instance(), instance()) }
    prototype { Fib332(instance(), instance()) }
    prototype { Fib333(instance(), instance()) }
    prototype { Fib334(instance(), instance()) }
    prototype { Fib335(instance(), instance()) }
    prototype { Fib336(instance(), instance()) }
    prototype { Fib337(instance(), instance()) }
    prototype { Fib338(instance(), instance()) }
    prototype { Fib339(instance(), instance()) }
    prototype { Fib340(instance(), instance()) }
    prototype { Fib341(instance(), instance()) }
    prototype { Fib342(instance(), instance()) }
    prototype { Fib343(instance(), instance()) }
    prototype { Fib344(instance(), instance()) }
    prototype { Fib345(instance(), instance()) }
    prototype { Fib346(instance(), instance()) }
    prototype { Fib347(instance(), instance()) }
    prototype { Fib348(instance(), instance()) }
    prototype { Fib349(instance(), instance()) }
    prototype { Fib350(instance(), instance()) }
    prototype { Fib351(instance(), instance()) }
    prototype { Fib352(instance(), instance()) }
    prototype { Fib353(instance(), instance()) }
    prototype { Fib354(instance(), instance()) }
    prototype { Fib355(instance(), instance()) }
    prototype { Fib356(instance(), instance()) }
    prototype { Fib357(instance(), instance()) }
    prototype { Fib358(instance(), instance()) }
    prototype { Fib359(instance(), instance()) }
    prototype { Fib360(instance(), instance()) }
    prototype { Fib361(instance(), instance()) }
    prototype { Fib362(instance(), instance()) }
    prototype { Fib363(instance(), instance()) }
    prototype { Fib364(instance(), instance()) }
    prototype { Fib365(instance(), instance()) }
    prototype { Fib366(instance(), instance()) }
    prototype { Fib367(instance(), instance()) }
    prototype { Fib368(instance(), instance()) }
    prototype { Fib369(instance(), instance()) }
    prototype { Fib370(instance(), instance()) }
    prototype { Fib371(instance(), instance()) }
    prototype { Fib372(instance(), instance()) }
    prototype { Fib373(instance(), instance()) }
    prototype { Fib374(instance(), instance()) }
    prototype { Fib375(instance(), instance()) }
    prototype { Fib376(instance(), instance()) }
    prototype { Fib377(instance(), instance()) }
    prototype { Fib378(instance(), instance()) }
    prototype { Fib379(instance(), instance()) }
    prototype { Fib380(instance(), instance()) }
    prototype { Fib381(instance(), instance()) }
    prototype { Fib382(instance(), instance()) }
    prototype { Fib383(instance(), instance()) }
    prototype { Fib384(instance(), instance()) }
    prototype { Fib385(instance(), instance()) }
    prototype { Fib386(instance(), instance()) }
    prototype { Fib387(instance(), instance()) }
    prototype { Fib388(instance(), instance()) }
    prototype { Fib389(instance(), instance()) }
    prototype { Fib390(instance(), instance()) }
    prototype { Fib391(instance(), instance()) }
    prototype { Fib392(instance(), instance()) }
    prototype { Fib393(instance(), instance()) }
    prototype { Fib394(instance(), instance()) }
    prototype { Fib395(instance(), instance()) }
    prototype { Fib396(instance(), instance()) }
    prototype { Fib397(instance(), instance()) }
    prototype { Fib398(instance(), instance()) }
    prototype { Fib399(instance(), instance()) }
    prototype { Fib400(instance(), instance()) }
    prototype { Fib401(instance(), instance()) }
    prototype { Fib402(instance(), instance()) }
    prototype { Fib403(instance(), instance()) }
    prototype { Fib404(instance(), instance()) }
    prototype { Fib405(instance(), instance()) }
    prototype { Fib406(instance(), instance()) }
    prototype { Fib407(instance(), instance()) }
    prototype { Fib408(instance(), instance()) }
    prototype { Fib409(instance(), instance()) }
    prototype { Fib410(instance(), instance()) }
    prototype { Fib411(instance(), instance()) }
    prototype { Fib412(instance(), instance()) }
    prototype { Fib413(instance(), instance()) }
    prototype { Fib414(instance(), instance()) }
    prototype { Fib415(instance(), instance()) }
    prototype { Fib416(instance(), instance()) }
    prototype { Fib417(instance(), instance()) }
    prototype { Fib418(instance(), instance()) }
    prototype { Fib419(instance(), instance()) }
    prototype { Fib420(instance(), instance()) }
    prototype { Fib421(instance(), instance()) }
    prototype { Fib422(instance(), instance()) }
    prototype { Fib423(instance(), instance()) }
    prototype { Fib424(instance(), instance()) }
    prototype { Fib425(instance(), instance()) }
    prototype { Fib426(instance(), instance()) }
    prototype { Fib427(instance(), instance()) }
    prototype { Fib428(instance(), instance()) }
    prototype { Fib429(instance(), instance()) }
    prototype { Fib430(instance(), instance()) }
    prototype { Fib431(instance(), instance()) }
    prototype { Fib432(instance(), instance()) }
    prototype { Fib433(instance(), instance()) }
    prototype { Fib434(instance(), instance()) }
    prototype { Fib435(instance(), instance()) }
    prototype { Fib436(instance(), instance()) }
    prototype { Fib437(instance(), instance()) }
    prototype { Fib438(instance(), instance()) }
    prototype { Fib439(instance(), instance()) }
    prototype { Fib440(instance(), instance()) }
    prototype { Fib441(instance(), instance()) }
    prototype { Fib442(instance(), instance()) }
    prototype { Fib443(instance(), instance()) }
    prototype { Fib444(instance(), instance()) }
    prototype { Fib445(instance(), instance()) }
    prototype { Fib446(instance(), instance()) }
    prototype { Fib447(instance(), instance()) }
    prototype { Fib448(instance(), instance()) }
    prototype { Fib449(instance(), instance()) }
    prototype { Fib450(instance(), instance()) }
}
