package com.sloydev.dependencyinjectionperformance.winter

import com.sloydev.dependencyinjectionperformance.FibonacciJava
import io.jentz.winter.component

val winterJavaComponent = component {
    prototype { FibonacciJava.Fib1() }
    prototype { FibonacciJava.Fib2() }
    prototype { FibonacciJava.Fib3(instance(), instance()) }
    prototype { FibonacciJava.Fib4(instance(), instance()) }
    prototype { FibonacciJava.Fib5(instance(), instance()) }
    prototype { FibonacciJava.Fib6(instance(), instance()) }
    prototype { FibonacciJava.Fib7(instance(), instance()) }
    prototype { FibonacciJava.Fib8(instance(), instance()) }
    prototype { FibonacciJava.Fib9(instance(), instance()) }
    prototype { FibonacciJava.Fib10(instance(), instance()) }
    prototype { FibonacciJava.Fib11(instance(), instance()) }
    prototype { FibonacciJava.Fib12(instance(), instance()) }
    prototype { FibonacciJava.Fib13(instance(), instance()) }
    prototype { FibonacciJava.Fib14(instance(), instance()) }
    prototype { FibonacciJava.Fib15(instance(), instance()) }
    prototype { FibonacciJava.Fib16(instance(), instance()) }
    prototype { FibonacciJava.Fib17(instance(), instance()) }
    prototype { FibonacciJava.Fib18(instance(), instance()) }
    prototype { FibonacciJava.Fib19(instance(), instance()) }
    prototype { FibonacciJava.Fib20(instance(), instance()) }
    prototype { FibonacciJava.Fib21(instance(), instance()) }
    prototype { FibonacciJava.Fib22(instance(), instance()) }
    prototype { FibonacciJava.Fib23(instance(), instance()) }
    prototype { FibonacciJava.Fib24(instance(), instance()) }
    prototype { FibonacciJava.Fib25(instance(), instance()) }
    prototype { FibonacciJava.Fib26(instance(), instance()) }
    prototype { FibonacciJava.Fib27(instance(), instance()) }
    prototype { FibonacciJava.Fib28(instance(), instance()) }
    prototype { FibonacciJava.Fib29(instance(), instance()) }
    prototype { FibonacciJava.Fib30(instance(), instance()) }
    prototype { FibonacciJava.Fib31(instance(), instance()) }
    prototype { FibonacciJava.Fib32(instance(), instance()) }
    prototype { FibonacciJava.Fib33(instance(), instance()) }
    prototype { FibonacciJava.Fib34(instance(), instance()) }
    prototype { FibonacciJava.Fib35(instance(), instance()) }
    prototype { FibonacciJava.Fib36(instance(), instance()) }
    prototype { FibonacciJava.Fib37(instance(), instance()) }
    prototype { FibonacciJava.Fib38(instance(), instance()) }
    prototype { FibonacciJava.Fib39(instance(), instance()) }
    prototype { FibonacciJava.Fib40(instance(), instance()) }
    prototype { FibonacciJava.Fib41(instance(), instance()) }
    prototype { FibonacciJava.Fib42(instance(), instance()) }
    prototype { FibonacciJava.Fib43(instance(), instance()) }
    prototype { FibonacciJava.Fib44(instance(), instance()) }
    prototype { FibonacciJava.Fib45(instance(), instance()) }
    prototype { FibonacciJava.Fib46(instance(), instance()) }
    prototype { FibonacciJava.Fib47(instance(), instance()) }
    prototype { FibonacciJava.Fib48(instance(), instance()) }
    prototype { FibonacciJava.Fib49(instance(), instance()) }
    prototype { FibonacciJava.Fib50(instance(), instance()) }
    prototype { FibonacciJava.Fib51(instance(), instance()) }
    prototype { FibonacciJava.Fib52(instance(), instance()) }
    prototype { FibonacciJava.Fib53(instance(), instance()) }
    prototype { FibonacciJava.Fib54(instance(), instance()) }
    prototype { FibonacciJava.Fib55(instance(), instance()) }
    prototype { FibonacciJava.Fib56(instance(), instance()) }
    prototype { FibonacciJava.Fib57(instance(), instance()) }
    prototype { FibonacciJava.Fib58(instance(), instance()) }
    prototype { FibonacciJava.Fib59(instance(), instance()) }
    prototype { FibonacciJava.Fib60(instance(), instance()) }
    prototype { FibonacciJava.Fib61(instance(), instance()) }
    prototype { FibonacciJava.Fib62(instance(), instance()) }
    prototype { FibonacciJava.Fib63(instance(), instance()) }
    prototype { FibonacciJava.Fib64(instance(), instance()) }
    prototype { FibonacciJava.Fib65(instance(), instance()) }
    prototype { FibonacciJava.Fib66(instance(), instance()) }
    prototype { FibonacciJava.Fib67(instance(), instance()) }
    prototype { FibonacciJava.Fib68(instance(), instance()) }
    prototype { FibonacciJava.Fib69(instance(), instance()) }
    prototype { FibonacciJava.Fib70(instance(), instance()) }
    prototype { FibonacciJava.Fib71(instance(), instance()) }
    prototype { FibonacciJava.Fib72(instance(), instance()) }
    prototype { FibonacciJava.Fib73(instance(), instance()) }
    prototype { FibonacciJava.Fib74(instance(), instance()) }
    prototype { FibonacciJava.Fib75(instance(), instance()) }
    prototype { FibonacciJava.Fib76(instance(), instance()) }
    prototype { FibonacciJava.Fib77(instance(), instance()) }
    prototype { FibonacciJava.Fib78(instance(), instance()) }
    prototype { FibonacciJava.Fib79(instance(), instance()) }
    prototype { FibonacciJava.Fib80(instance(), instance()) }
    prototype { FibonacciJava.Fib81(instance(), instance()) }
    prototype { FibonacciJava.Fib82(instance(), instance()) }
    prototype { FibonacciJava.Fib83(instance(), instance()) }
    prototype { FibonacciJava.Fib84(instance(), instance()) }
    prototype { FibonacciJava.Fib85(instance(), instance()) }
    prototype { FibonacciJava.Fib86(instance(), instance()) }
    prototype { FibonacciJava.Fib87(instance(), instance()) }
    prototype { FibonacciJava.Fib88(instance(), instance()) }
    prototype { FibonacciJava.Fib89(instance(), instance()) }
    prototype { FibonacciJava.Fib90(instance(), instance()) }
    prototype { FibonacciJava.Fib91(instance(), instance()) }
    prototype { FibonacciJava.Fib92(instance(), instance()) }
    prototype { FibonacciJava.Fib93(instance(), instance()) }
    prototype { FibonacciJava.Fib94(instance(), instance()) }
    prototype { FibonacciJava.Fib95(instance(), instance()) }
    prototype { FibonacciJava.Fib96(instance(), instance()) }
    prototype { FibonacciJava.Fib97(instance(), instance()) }
    prototype { FibonacciJava.Fib98(instance(), instance()) }
    prototype { FibonacciJava.Fib99(instance(), instance()) }
    prototype { FibonacciJava.Fib100(instance(), instance()) }
    prototype { FibonacciJava.Fib101(instance(), instance()) }
    prototype { FibonacciJava.Fib102(instance(), instance()) }
    prototype { FibonacciJava.Fib103(instance(), instance()) }
    prototype { FibonacciJava.Fib104(instance(), instance()) }
    prototype { FibonacciJava.Fib105(instance(), instance()) }
    prototype { FibonacciJava.Fib106(instance(), instance()) }
    prototype { FibonacciJava.Fib107(instance(), instance()) }
    prototype { FibonacciJava.Fib108(instance(), instance()) }
    prototype { FibonacciJava.Fib109(instance(), instance()) }
    prototype { FibonacciJava.Fib110(instance(), instance()) }
    prototype { FibonacciJava.Fib111(instance(), instance()) }
    prototype { FibonacciJava.Fib112(instance(), instance()) }
    prototype { FibonacciJava.Fib113(instance(), instance()) }
    prototype { FibonacciJava.Fib114(instance(), instance()) }
    prototype { FibonacciJava.Fib115(instance(), instance()) }
    prototype { FibonacciJava.Fib116(instance(), instance()) }
    prototype { FibonacciJava.Fib117(instance(), instance()) }
    prototype { FibonacciJava.Fib118(instance(), instance()) }
    prototype { FibonacciJava.Fib119(instance(), instance()) }
    prototype { FibonacciJava.Fib120(instance(), instance()) }
    prototype { FibonacciJava.Fib121(instance(), instance()) }
    prototype { FibonacciJava.Fib122(instance(), instance()) }
    prototype { FibonacciJava.Fib123(instance(), instance()) }
    prototype { FibonacciJava.Fib124(instance(), instance()) }
    prototype { FibonacciJava.Fib125(instance(), instance()) }
    prototype { FibonacciJava.Fib126(instance(), instance()) }
    prototype { FibonacciJava.Fib127(instance(), instance()) }
    prototype { FibonacciJava.Fib128(instance(), instance()) }
    prototype { FibonacciJava.Fib129(instance(), instance()) }
    prototype { FibonacciJava.Fib130(instance(), instance()) }
    prototype { FibonacciJava.Fib131(instance(), instance()) }
    prototype { FibonacciJava.Fib132(instance(), instance()) }
    prototype { FibonacciJava.Fib133(instance(), instance()) }
    prototype { FibonacciJava.Fib134(instance(), instance()) }
    prototype { FibonacciJava.Fib135(instance(), instance()) }
    prototype { FibonacciJava.Fib136(instance(), instance()) }
    prototype { FibonacciJava.Fib137(instance(), instance()) }
    prototype { FibonacciJava.Fib138(instance(), instance()) }
    prototype { FibonacciJava.Fib139(instance(), instance()) }
    prototype { FibonacciJava.Fib140(instance(), instance()) }
    prototype { FibonacciJava.Fib141(instance(), instance()) }
    prototype { FibonacciJava.Fib142(instance(), instance()) }
    prototype { FibonacciJava.Fib143(instance(), instance()) }
    prototype { FibonacciJava.Fib144(instance(), instance()) }
    prototype { FibonacciJava.Fib145(instance(), instance()) }
    prototype { FibonacciJava.Fib146(instance(), instance()) }
    prototype { FibonacciJava.Fib147(instance(), instance()) }
    prototype { FibonacciJava.Fib148(instance(), instance()) }
    prototype { FibonacciJava.Fib149(instance(), instance()) }
    prototype { FibonacciJava.Fib150(instance(), instance()) }
    prototype { FibonacciJava.Fib151(instance(), instance()) }
    prototype { FibonacciJava.Fib152(instance(), instance()) }
    prototype { FibonacciJava.Fib153(instance(), instance()) }
    prototype { FibonacciJava.Fib154(instance(), instance()) }
    prototype { FibonacciJava.Fib155(instance(), instance()) }
    prototype { FibonacciJava.Fib156(instance(), instance()) }
    prototype { FibonacciJava.Fib157(instance(), instance()) }
    prototype { FibonacciJava.Fib158(instance(), instance()) }
    prototype { FibonacciJava.Fib159(instance(), instance()) }
    prototype { FibonacciJava.Fib160(instance(), instance()) }
    prototype { FibonacciJava.Fib161(instance(), instance()) }
    prototype { FibonacciJava.Fib162(instance(), instance()) }
    prototype { FibonacciJava.Fib163(instance(), instance()) }
    prototype { FibonacciJava.Fib164(instance(), instance()) }
    prototype { FibonacciJava.Fib165(instance(), instance()) }
    prototype { FibonacciJava.Fib166(instance(), instance()) }
    prototype { FibonacciJava.Fib167(instance(), instance()) }
    prototype { FibonacciJava.Fib168(instance(), instance()) }
    prototype { FibonacciJava.Fib169(instance(), instance()) }
    prototype { FibonacciJava.Fib170(instance(), instance()) }
    prototype { FibonacciJava.Fib171(instance(), instance()) }
    prototype { FibonacciJava.Fib172(instance(), instance()) }
    prototype { FibonacciJava.Fib173(instance(), instance()) }
    prototype { FibonacciJava.Fib174(instance(), instance()) }
    prototype { FibonacciJava.Fib175(instance(), instance()) }
    prototype { FibonacciJava.Fib176(instance(), instance()) }
    prototype { FibonacciJava.Fib177(instance(), instance()) }
    prototype { FibonacciJava.Fib178(instance(), instance()) }
    prototype { FibonacciJava.Fib179(instance(), instance()) }
    prototype { FibonacciJava.Fib180(instance(), instance()) }
    prototype { FibonacciJava.Fib181(instance(), instance()) }
    prototype { FibonacciJava.Fib182(instance(), instance()) }
    prototype { FibonacciJava.Fib183(instance(), instance()) }
    prototype { FibonacciJava.Fib184(instance(), instance()) }
    prototype { FibonacciJava.Fib185(instance(), instance()) }
    prototype { FibonacciJava.Fib186(instance(), instance()) }
    prototype { FibonacciJava.Fib187(instance(), instance()) }
    prototype { FibonacciJava.Fib188(instance(), instance()) }
    prototype { FibonacciJava.Fib189(instance(), instance()) }
    prototype { FibonacciJava.Fib190(instance(), instance()) }
    prototype { FibonacciJava.Fib191(instance(), instance()) }
    prototype { FibonacciJava.Fib192(instance(), instance()) }
    prototype { FibonacciJava.Fib193(instance(), instance()) }
    prototype { FibonacciJava.Fib194(instance(), instance()) }
    prototype { FibonacciJava.Fib195(instance(), instance()) }
    prototype { FibonacciJava.Fib196(instance(), instance()) }
    prototype { FibonacciJava.Fib197(instance(), instance()) }
    prototype { FibonacciJava.Fib198(instance(), instance()) }
    prototype { FibonacciJava.Fib199(instance(), instance()) }
    prototype { FibonacciJava.Fib200(instance(), instance()) }
    prototype { FibonacciJava.Fib201(instance(), instance()) }
    prototype { FibonacciJava.Fib202(instance(), instance()) }
    prototype { FibonacciJava.Fib203(instance(), instance()) }
    prototype { FibonacciJava.Fib204(instance(), instance()) }
    prototype { FibonacciJava.Fib205(instance(), instance()) }
    prototype { FibonacciJava.Fib206(instance(), instance()) }
    prototype { FibonacciJava.Fib207(instance(), instance()) }
    prototype { FibonacciJava.Fib208(instance(), instance()) }
    prototype { FibonacciJava.Fib209(instance(), instance()) }
    prototype { FibonacciJava.Fib210(instance(), instance()) }
    prototype { FibonacciJava.Fib211(instance(), instance()) }
    prototype { FibonacciJava.Fib212(instance(), instance()) }
    prototype { FibonacciJava.Fib213(instance(), instance()) }
    prototype { FibonacciJava.Fib214(instance(), instance()) }
    prototype { FibonacciJava.Fib215(instance(), instance()) }
    prototype { FibonacciJava.Fib216(instance(), instance()) }
    prototype { FibonacciJava.Fib217(instance(), instance()) }
    prototype { FibonacciJava.Fib218(instance(), instance()) }
    prototype { FibonacciJava.Fib219(instance(), instance()) }
    prototype { FibonacciJava.Fib220(instance(), instance()) }
    prototype { FibonacciJava.Fib221(instance(), instance()) }
    prototype { FibonacciJava.Fib222(instance(), instance()) }
    prototype { FibonacciJava.Fib223(instance(), instance()) }
    prototype { FibonacciJava.Fib224(instance(), instance()) }
    prototype { FibonacciJava.Fib225(instance(), instance()) }
    prototype { FibonacciJava.Fib226(instance(), instance()) }
    prototype { FibonacciJava.Fib227(instance(), instance()) }
    prototype { FibonacciJava.Fib228(instance(), instance()) }
    prototype { FibonacciJava.Fib229(instance(), instance()) }
    prototype { FibonacciJava.Fib230(instance(), instance()) }
    prototype { FibonacciJava.Fib231(instance(), instance()) }
    prototype { FibonacciJava.Fib232(instance(), instance()) }
    prototype { FibonacciJava.Fib233(instance(), instance()) }
    prototype { FibonacciJava.Fib234(instance(), instance()) }
    prototype { FibonacciJava.Fib235(instance(), instance()) }
    prototype { FibonacciJava.Fib236(instance(), instance()) }
    prototype { FibonacciJava.Fib237(instance(), instance()) }
    prototype { FibonacciJava.Fib238(instance(), instance()) }
    prototype { FibonacciJava.Fib239(instance(), instance()) }
    prototype { FibonacciJava.Fib240(instance(), instance()) }
    prototype { FibonacciJava.Fib241(instance(), instance()) }
    prototype { FibonacciJava.Fib242(instance(), instance()) }
    prototype { FibonacciJava.Fib243(instance(), instance()) }
    prototype { FibonacciJava.Fib244(instance(), instance()) }
    prototype { FibonacciJava.Fib245(instance(), instance()) }
    prototype { FibonacciJava.Fib246(instance(), instance()) }
    prototype { FibonacciJava.Fib247(instance(), instance()) }
    prototype { FibonacciJava.Fib248(instance(), instance()) }
    prototype { FibonacciJava.Fib249(instance(), instance()) }
    prototype { FibonacciJava.Fib250(instance(), instance()) }
    prototype { FibonacciJava.Fib251(instance(), instance()) }
    prototype { FibonacciJava.Fib252(instance(), instance()) }
    prototype { FibonacciJava.Fib253(instance(), instance()) }
    prototype { FibonacciJava.Fib254(instance(), instance()) }
    prototype { FibonacciJava.Fib255(instance(), instance()) }
    prototype { FibonacciJava.Fib256(instance(), instance()) }
    prototype { FibonacciJava.Fib257(instance(), instance()) }
    prototype { FibonacciJava.Fib258(instance(), instance()) }
    prototype { FibonacciJava.Fib259(instance(), instance()) }
    prototype { FibonacciJava.Fib260(instance(), instance()) }
    prototype { FibonacciJava.Fib261(instance(), instance()) }
    prototype { FibonacciJava.Fib262(instance(), instance()) }
    prototype { FibonacciJava.Fib263(instance(), instance()) }
    prototype { FibonacciJava.Fib264(instance(), instance()) }
    prototype { FibonacciJava.Fib265(instance(), instance()) }
    prototype { FibonacciJava.Fib266(instance(), instance()) }
    prototype { FibonacciJava.Fib267(instance(), instance()) }
    prototype { FibonacciJava.Fib268(instance(), instance()) }
    prototype { FibonacciJava.Fib269(instance(), instance()) }
    prototype { FibonacciJava.Fib270(instance(), instance()) }
    prototype { FibonacciJava.Fib271(instance(), instance()) }
    prototype { FibonacciJava.Fib272(instance(), instance()) }
    prototype { FibonacciJava.Fib273(instance(), instance()) }
    prototype { FibonacciJava.Fib274(instance(), instance()) }
    prototype { FibonacciJava.Fib275(instance(), instance()) }
    prototype { FibonacciJava.Fib276(instance(), instance()) }
    prototype { FibonacciJava.Fib277(instance(), instance()) }
    prototype { FibonacciJava.Fib278(instance(), instance()) }
    prototype { FibonacciJava.Fib279(instance(), instance()) }
    prototype { FibonacciJava.Fib280(instance(), instance()) }
    prototype { FibonacciJava.Fib281(instance(), instance()) }
    prototype { FibonacciJava.Fib282(instance(), instance()) }
    prototype { FibonacciJava.Fib283(instance(), instance()) }
    prototype { FibonacciJava.Fib284(instance(), instance()) }
    prototype { FibonacciJava.Fib285(instance(), instance()) }
    prototype { FibonacciJava.Fib286(instance(), instance()) }
    prototype { FibonacciJava.Fib287(instance(), instance()) }
    prototype { FibonacciJava.Fib288(instance(), instance()) }
    prototype { FibonacciJava.Fib289(instance(), instance()) }
    prototype { FibonacciJava.Fib290(instance(), instance()) }
    prototype { FibonacciJava.Fib291(instance(), instance()) }
    prototype { FibonacciJava.Fib292(instance(), instance()) }
    prototype { FibonacciJava.Fib293(instance(), instance()) }
    prototype { FibonacciJava.Fib294(instance(), instance()) }
    prototype { FibonacciJava.Fib295(instance(), instance()) }
    prototype { FibonacciJava.Fib296(instance(), instance()) }
    prototype { FibonacciJava.Fib297(instance(), instance()) }
    prototype { FibonacciJava.Fib298(instance(), instance()) }
    prototype { FibonacciJava.Fib299(instance(), instance()) }
    prototype { FibonacciJava.Fib300(instance(), instance()) }
    prototype { FibonacciJava.Fib301(instance(), instance()) }
    prototype { FibonacciJava.Fib302(instance(), instance()) }
    prototype { FibonacciJava.Fib303(instance(), instance()) }
    prototype { FibonacciJava.Fib304(instance(), instance()) }
    prototype { FibonacciJava.Fib305(instance(), instance()) }
    prototype { FibonacciJava.Fib306(instance(), instance()) }
    prototype { FibonacciJava.Fib307(instance(), instance()) }
    prototype { FibonacciJava.Fib308(instance(), instance()) }
    prototype { FibonacciJava.Fib309(instance(), instance()) }
    prototype { FibonacciJava.Fib310(instance(), instance()) }
    prototype { FibonacciJava.Fib311(instance(), instance()) }
    prototype { FibonacciJava.Fib312(instance(), instance()) }
    prototype { FibonacciJava.Fib313(instance(), instance()) }
    prototype { FibonacciJava.Fib314(instance(), instance()) }
    prototype { FibonacciJava.Fib315(instance(), instance()) }
    prototype { FibonacciJava.Fib316(instance(), instance()) }
    prototype { FibonacciJava.Fib317(instance(), instance()) }
    prototype { FibonacciJava.Fib318(instance(), instance()) }
    prototype { FibonacciJava.Fib319(instance(), instance()) }
    prototype { FibonacciJava.Fib320(instance(), instance()) }
    prototype { FibonacciJava.Fib321(instance(), instance()) }
    prototype { FibonacciJava.Fib322(instance(), instance()) }
    prototype { FibonacciJava.Fib323(instance(), instance()) }
    prototype { FibonacciJava.Fib324(instance(), instance()) }
    prototype { FibonacciJava.Fib325(instance(), instance()) }
    prototype { FibonacciJava.Fib326(instance(), instance()) }
    prototype { FibonacciJava.Fib327(instance(), instance()) }
    prototype { FibonacciJava.Fib328(instance(), instance()) }
    prototype { FibonacciJava.Fib329(instance(), instance()) }
    prototype { FibonacciJava.Fib330(instance(), instance()) }
    prototype { FibonacciJava.Fib331(instance(), instance()) }
    prototype { FibonacciJava.Fib332(instance(), instance()) }
    prototype { FibonacciJava.Fib333(instance(), instance()) }
    prototype { FibonacciJava.Fib334(instance(), instance()) }
    prototype { FibonacciJava.Fib335(instance(), instance()) }
    prototype { FibonacciJava.Fib336(instance(), instance()) }
    prototype { FibonacciJava.Fib337(instance(), instance()) }
    prototype { FibonacciJava.Fib338(instance(), instance()) }
    prototype { FibonacciJava.Fib339(instance(), instance()) }
    prototype { FibonacciJava.Fib340(instance(), instance()) }
    prototype { FibonacciJava.Fib341(instance(), instance()) }
    prototype { FibonacciJava.Fib342(instance(), instance()) }
    prototype { FibonacciJava.Fib343(instance(), instance()) }
    prototype { FibonacciJava.Fib344(instance(), instance()) }
    prototype { FibonacciJava.Fib345(instance(), instance()) }
    prototype { FibonacciJava.Fib346(instance(), instance()) }
    prototype { FibonacciJava.Fib347(instance(), instance()) }
    prototype { FibonacciJava.Fib348(instance(), instance()) }
    prototype { FibonacciJava.Fib349(instance(), instance()) }
    prototype { FibonacciJava.Fib350(instance(), instance()) }
    prototype { FibonacciJava.Fib351(instance(), instance()) }
    prototype { FibonacciJava.Fib352(instance(), instance()) }
    prototype { FibonacciJava.Fib353(instance(), instance()) }
    prototype { FibonacciJava.Fib354(instance(), instance()) }
    prototype { FibonacciJava.Fib355(instance(), instance()) }
    prototype { FibonacciJava.Fib356(instance(), instance()) }
    prototype { FibonacciJava.Fib357(instance(), instance()) }
    prototype { FibonacciJava.Fib358(instance(), instance()) }
    prototype { FibonacciJava.Fib359(instance(), instance()) }
    prototype { FibonacciJava.Fib360(instance(), instance()) }
    prototype { FibonacciJava.Fib361(instance(), instance()) }
    prototype { FibonacciJava.Fib362(instance(), instance()) }
    prototype { FibonacciJava.Fib363(instance(), instance()) }
    prototype { FibonacciJava.Fib364(instance(), instance()) }
    prototype { FibonacciJava.Fib365(instance(), instance()) }
    prototype { FibonacciJava.Fib366(instance(), instance()) }
    prototype { FibonacciJava.Fib367(instance(), instance()) }
    prototype { FibonacciJava.Fib368(instance(), instance()) }
    prototype { FibonacciJava.Fib369(instance(), instance()) }
    prototype { FibonacciJava.Fib370(instance(), instance()) }
    prototype { FibonacciJava.Fib371(instance(), instance()) }
    prototype { FibonacciJava.Fib372(instance(), instance()) }
    prototype { FibonacciJava.Fib373(instance(), instance()) }
    prototype { FibonacciJava.Fib374(instance(), instance()) }
    prototype { FibonacciJava.Fib375(instance(), instance()) }
    prototype { FibonacciJava.Fib376(instance(), instance()) }
    prototype { FibonacciJava.Fib377(instance(), instance()) }
    prototype { FibonacciJava.Fib378(instance(), instance()) }
    prototype { FibonacciJava.Fib379(instance(), instance()) }
    prototype { FibonacciJava.Fib380(instance(), instance()) }
    prototype { FibonacciJava.Fib381(instance(), instance()) }
    prototype { FibonacciJava.Fib382(instance(), instance()) }
    prototype { FibonacciJava.Fib383(instance(), instance()) }
    prototype { FibonacciJava.Fib384(instance(), instance()) }
    prototype { FibonacciJava.Fib385(instance(), instance()) }
    prototype { FibonacciJava.Fib386(instance(), instance()) }
    prototype { FibonacciJava.Fib387(instance(), instance()) }
    prototype { FibonacciJava.Fib388(instance(), instance()) }
    prototype { FibonacciJava.Fib389(instance(), instance()) }
    prototype { FibonacciJava.Fib390(instance(), instance()) }
    prototype { FibonacciJava.Fib391(instance(), instance()) }
    prototype { FibonacciJava.Fib392(instance(), instance()) }
    prototype { FibonacciJava.Fib393(instance(), instance()) }
    prototype { FibonacciJava.Fib394(instance(), instance()) }
    prototype { FibonacciJava.Fib395(instance(), instance()) }
    prototype { FibonacciJava.Fib396(instance(), instance()) }
    prototype { FibonacciJava.Fib397(instance(), instance()) }
    prototype { FibonacciJava.Fib398(instance(), instance()) }
    prototype { FibonacciJava.Fib399(instance(), instance()) }
    prototype { FibonacciJava.Fib400(instance(), instance()) }
    prototype { FibonacciJava.Fib401(instance(), instance()) }
    prototype { FibonacciJava.Fib402(instance(), instance()) }
    prototype { FibonacciJava.Fib403(instance(), instance()) }
    prototype { FibonacciJava.Fib404(instance(), instance()) }
    prototype { FibonacciJava.Fib405(instance(), instance()) }
    prototype { FibonacciJava.Fib406(instance(), instance()) }
    prototype { FibonacciJava.Fib407(instance(), instance()) }
    prototype { FibonacciJava.Fib408(instance(), instance()) }
    prototype { FibonacciJava.Fib409(instance(), instance()) }
    prototype { FibonacciJava.Fib410(instance(), instance()) }
    prototype { FibonacciJava.Fib411(instance(), instance()) }
    prototype { FibonacciJava.Fib412(instance(), instance()) }
    prototype { FibonacciJava.Fib413(instance(), instance()) }
    prototype { FibonacciJava.Fib414(instance(), instance()) }
    prototype { FibonacciJava.Fib415(instance(), instance()) }
    prototype { FibonacciJava.Fib416(instance(), instance()) }
    prototype { FibonacciJava.Fib417(instance(), instance()) }
    prototype { FibonacciJava.Fib418(instance(), instance()) }
    prototype { FibonacciJava.Fib419(instance(), instance()) }
    prototype { FibonacciJava.Fib420(instance(), instance()) }
    prototype { FibonacciJava.Fib421(instance(), instance()) }
    prototype { FibonacciJava.Fib422(instance(), instance()) }
    prototype { FibonacciJava.Fib423(instance(), instance()) }
    prototype { FibonacciJava.Fib424(instance(), instance()) }
    prototype { FibonacciJava.Fib425(instance(), instance()) }
    prototype { FibonacciJava.Fib426(instance(), instance()) }
    prototype { FibonacciJava.Fib427(instance(), instance()) }
    prototype { FibonacciJava.Fib428(instance(), instance()) }
    prototype { FibonacciJava.Fib429(instance(), instance()) }
    prototype { FibonacciJava.Fib430(instance(), instance()) }
    prototype { FibonacciJava.Fib431(instance(), instance()) }
    prototype { FibonacciJava.Fib432(instance(), instance()) }
    prototype { FibonacciJava.Fib433(instance(), instance()) }
    prototype { FibonacciJava.Fib434(instance(), instance()) }
    prototype { FibonacciJava.Fib435(instance(), instance()) }
    prototype { FibonacciJava.Fib436(instance(), instance()) }
    prototype { FibonacciJava.Fib437(instance(), instance()) }
    prototype { FibonacciJava.Fib438(instance(), instance()) }
    prototype { FibonacciJava.Fib439(instance(), instance()) }
    prototype { FibonacciJava.Fib440(instance(), instance()) }
    prototype { FibonacciJava.Fib441(instance(), instance()) }
    prototype { FibonacciJava.Fib442(instance(), instance()) }
    prototype { FibonacciJava.Fib443(instance(), instance()) }
    prototype { FibonacciJava.Fib444(instance(), instance()) }
    prototype { FibonacciJava.Fib445(instance(), instance()) }
    prototype { FibonacciJava.Fib446(instance(), instance()) }
    prototype { FibonacciJava.Fib447(instance(), instance()) }
    prototype { FibonacciJava.Fib448(instance(), instance()) }
    prototype { FibonacciJava.Fib449(instance(), instance()) }
    prototype { FibonacciJava.Fib450(instance(), instance()) }
}